import NavBar from "@/components/NavBar/NavBar";
import { Roboto } from "next/font/google";
import "./global.css";
export const metadata = {
  title: "Mi proyecto de Next.js",
  description: "Generated by Guillote",
  keywords: "nextjs, react, guillote",
  publisher: "Guillote",
};
const roboto = Roboto({
  display: "swap",
  family: "Roboto",
  fallback: "sans-serif",
  weight: ["300", "400", "500", "700", "900"],
  subsets: ["latin"],
  styles: ["italic", "regular"],
  preload: true,
  preconnect: true,
  useMinify: true,
  usePreload: true,
  usePreconnect: true,
  optimizeSpeed: true,
});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
